const exportedModules = require('./exports.json');
const fs = require('fs');
const path = require('path');
const requires = [];
const BUNDLE_PATH = './client/src/bundles/exports.js';

requires.push('// This file is generated by generate-exports.js in the module root. Do not modify');
Object.keys(exportedModules).forEach(globalName => {
  if (exportedModules.hasOwnProperty(globalName)) {
    const modulePath = exportedModules[globalName];
    requires.push(`require('expose-loader?${globalName}!${modulePath}');`);
  }
});

fs.writeFile(BUNDLE_PATH, requires.join('\n'), err => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  process.exit(0);
});

